#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import os

lib = bld.shlib (
  features = 'c cshlib',
  target = 'indicator',
  vapi_dirs = '../../vapi ../../libdiodon',
  uselib = 'APPINDICATOR PEAS',
  use = 'libdiodon',
  install_binding = False,
  cflags = ['-include', 'config.h'],
  packages = 'appindicator3-0.1 libpeas-1.0',
  source = bld.path.ant_glob (incl='**/*.vala'))

lib.install_path = os.path.join(bld.env['PLUGINS_DIR'], lib.target)

bld.new_task_gen (
  features = 'intltool_in',
  podir = '../../po',
  source = 'indicator.plugin.in',
  flags = ["-d", "-q", "-u", "-c"],
  install_path = lib.install_path)
