#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import Options

if bld.env['UNITYLENS']:
    bld.add_subdirs('unitylens')
    
if bld.env['INDICATOR']:
    bld.add_subdirs('indicator')

if bld.env['ZEITGEIST']:
    bld.add_subdirs('zeitgeist')
