#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import Options

if bld.env['UNITYSCOPE']:
    bld.add_subdirs('unityscope')
    
if bld.env['INDICATOR']:
    bld.add_subdirs('indicator')
