#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import os

lib = bld.shlib (
  features = 'c cshlib disable_binding',
  target = 'unitylens',
  vapi_dirs = '../../vapi ../../libdiodon',
  uselib = 'GTK PEAS UNITY DEE',
  use = 'libdiodon',
  cflags = ['-include', 'config.h'],
  packages = 'gtk+-3.0 libpeas-1.0 dee-1.0 gio-2.0 unity config',
  source = bld.path.ant_glob (incl='**/*.vala'))

lib.install_path = os.path.join(bld.env['PLUGINS_DIR'], lib.target)

bld.new_task_gen (
  features = "subst",
  source= "diodon.lens.in.in",
  target= "diodon.lens.in",
  GETTEXT_PACKAGE = bld.env['GETTEXT_PACKAGE'],
  BUSNAME = bld.env['BUSNAME'],
  BUSOBJECTPATH = bld.env['BUSOBJECTPATH'])
    
bld.new_task_gen (
  features = 'intltool_in',
  podir = '../../po',
  source = 'diodon.lens.in',
  flags = ["-d", "-q", "-u", "-c"],
  install_path = "${DATADIR}/unity/lenses/diodon")
 
bld.new_task_gen (
  features = 'intltool_in',
  podir = '../../po',
  source = 'unitylens.plugin.in',
  flags = ["-d", "-q", "-u", "-c"],
  install_path = lib.install_path)

