#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import os

lib = bld.shlib (
  features = 'c cshlib',
  target = 'unityscope',
  vapi_dirs = '../../vapi ../../libdiodon',
  uselib = 'GTK PEAS UNITY',
  use = 'libdiodon',
  cflags = ['-include', 'config.h'],
  install_binding = False,
  packages = 'gtk+-3.0 libpeas-1.0 gio-2.0 unity config',
  source = bld.path.ant_glob (incl='**/*.vala'))

lib.install_path = os.path.join(bld.env['PLUGINS_DIR'], lib.target)

bld.new_task_gen (
  features = 'intltool_in',
  podir = '../../po',
  source = 'unityscope.plugin.in',
  flags = ["-d", "-q", "-u", "-c"],
  install_path = lib.install_path)

