#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import Options

prog = bld.new_task_gen (
  features = 'c cprogram',
  target = 'diodon',
  vapi_dirs = '../vapi ../libdiodon',
  uselib = 'GTK PEAS',
  use = 'libdiodon',
  cflags = ['-include', 'config.h'],
  packages = 'gtk+-3.0 libpeas-1.0 libpeas-gtk-1.0 config',
  source = 'main.vala')

