#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

from waflib import Options

prog = bld(
  features = 'c cprogram',
  target = 'diodon',
  vapi_dirs = '../vapi ../libdiodon',
  uselib = 'GTK GIOUNIX',
  use = 'libdiodon',
  cflags = ['-include', 'config.h'],
  packages = 'gtk+-3.0 gio-unix-2.0 config',
  source = 'main.vala')

