#! /usr/bin/env python
# encoding: utf-8

bld.new_task_gen (
    features = "subst",
    source= "net.launchpad.Diodon.gschema.xml.in.in",
    target= "net.launchpad.Diodon.gschema.xml.in",
    GETTEXT_PACKAGE = bld.env['GETTEXT_PACKAGE'])

bld.new_task_gen (
  features = 'intltool_in',
  podir = '.', # no translations should get added to gschema file
  source = 'net.launchpad.Diodon.gschema.xml.in',
  install_path = '',  # do not install it
  flags = ["-x", "-q", "-u", "-c"])
  
task = bld.new_task_gen (
    features = 'glib2')    
task.add_settings_schemas ('net.launchpad.Diodon.gschema.xml')

bld.new_task_gen (
  features = 'intltool_in',
  podir = '../po',
  source = 'diodon.desktop.in',
  flags = ["-d", "-q", "-u", "-c"],
  install_path = "${DATADIR}/applications")

if bld.env['HAVE_UNITY'] and bld.env['HAVE_DEE']:
    bld.new_task_gen (
        features = "subst",
        source= "diodon.lens.in.in",
        target= "diodon.lens.in",
        GETTEXT_PACKAGE = bld.env['GETTEXT_PACKAGE'],
        BUSNAME = bld.env['BUSNAME'],
        BUSOBJECTPATH = bld.env['BUSOBJECTPATH'])
        
    bld.new_task_gen (
      features = 'intltool_in',
      podir = '../po',
      source = 'diodon.lens.in',
      flags = ["-d", "-q", "-u", "-c"],
      install_path = "${DATADIR}/unity/lenses/diodon")

bld.install_files('${SYSCONFDIR}/xdg/autostart', 'diodon.desktop')
bld.install_files('${DATADIR}/diodon', 'preferences.ui')
bld.install_files('${MANDIR}/man1', 'diodon.1.gz')

