#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import Options

lib = bld.shlib (
  features = 'c cshlib',
  target = 'diodon',
  vnum = bld.env['VERSION'],
  vapi_dirs = '../vapi',
  uselib = 'GTK GEE APPINDICATOR XML X11 GDKX GIO GIOUNIX PEAS PEASGTK',
  cflags = ['-include', 'config.h'],
  packages = 'gtk+-3.0 gee-1.0 gio-2.0 gio-unix-2.0 appindicator3-0.1 libxml-2.0 x11 gdk-x11-3.0 libpeas-1.0 libpeas-gtk-1.0 config',
  source = bld.path.ant_glob (incl='**/*.vala'))

if bld.env['HAVE_UNITY'] and bld.env['HAVE_DEE']:
    lib.env.append_value ('VALAFLAGS', '--define=UNITY_LENS')
    lib.uselib += ' DEE UNITY'
    lib.packages += ' dee-1.0 unity'
   
