#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import Options

prog = bld.new_task_gen (
  features = 'cc cprogram',
  target = 'diodon',
  vapi_dirs = '../vapi',
  uselib = 'GTK GEE APPINDICATOR XML',
  ccflags = ['-include', 'config.h'],
  packages = 'gtk+-2.0 gee-1.0 appindicator-0.1 libxml-2.0',
  source = bld.path.ant_glob (incl='**/*.vala'))

if Options.options.debug:
  prog.env = bld.env_of_name ('debug').copy ()
