#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import Options

prog = bld.new_task_gen (
  features = 'c cprogram',
  target = 'diodon',
  vapi_dirs = '../vapi',
  uselib = 'GTK GEE APPINDICATOR XML GCONF X11 GDKX GIO',
  cflags = ['-include', 'config.h'],
  packages = 'gtk+-2.0 gee-1.0 gio-2.0 appindicator-0.1 libxml-2.0 gconf-2.0 x11 gdk-x11-2.0 config',
  source = bld.path.ant_glob (incl='**/*.vala'))

if bld.env['HAVE_UNITY'] and bld.env['HAVE_DEE']:
    prog.env.append_value ('VALAFLAGS', '--define=UNITY_LENS')
    prog.uselib += ' DEE UNITY'
    prog.packages += ' dee-1.0 unity'
  
if Options.options.debug:
    prog.env = bld.env_of_name ('debug').copy ()
  
