#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2012

import os

lib = bld.shlib (
  features = 'c cshlib disable_binding',
  target = 'zeitgeist',
  vapi_dirs = '../../vapi ../../libdiodon',
  uselib = 'ZEITGEIST PEAS X11 GDKX',
  use = 'libdiodon',
  cflags = ['-include', 'config.h'],
  packages = 'zeitgeist-1.0 libpeas-1.0 x11 gdk-x11-3.0',
  source = bld.path.ant_glob (incl='**/*.vala'))

lib.install_path = os.path.join(bld.env['PLUGINS_DIR'], lib.target)

bld.new_task_gen (
  features = 'intltool_in',
  podir = '../../po',
  source = 'zeitgeist.plugin.in',
  flags = ["-d", "-q", "-u", "-c"],
  install_path = lib.install_path)
