#! /usr/bin/env python
# encoding: utf-8
# Oliver Sauder, 2010

import Options

prog = bld.new_task_gen (
  features = 'c cprogram',
  target = 'unity-scope-diodon',
  vapi_dirs = '../vapi ../libdiodon',
  uselib = 'GTK UNITY GEE',
  use = 'libdiodon',
  cflags = ['-include', 'config.h'],
  packages = 'gtk+-3.0 unity config gee-0.8',
  source = 'unity-scope-diodon.vala')

prog.install_path = bld.env['LIBDIR_DIODON']

bld.new_task_gen (
  features = "subst",
  source= "clipboard.scope.in.in",
  target= "clipboard.scope.in",
  BUSNAME = bld.env['BUSNAME'],
  BUSOBJECTPATH = bld.env['BUSOBJECTPATH'])

bld.new_task_gen (
  features = 'intltool_in',
  podir = '../po',
  source = 'clipboard.scope.in',
  flags = ["-d", "-q", "-u", "-c"],
  install_path = "${DATADIR}/unity/scopes")

bld.new_task_gen (
  features = "subst",
  source= "unity-scope-diodon.service.in",
  target= "unity-scope-diodon.service",
  BUSNAME = bld.env['BUSNAME'],
  LIBDIR_DIODON = bld.env['LIBDIR_DIODON'],
  install_path = "${DATADIR}/dbus-1/services")

bld.install_files('${DATADIR}/glib-2.0/schemas', 'unity-scope-diodon.gschema.override')

